### ISSUE TITLE
fix template dependabot conflicts

### ISSUE THREAD

**Issue by pmrowla** [iterative/py-template#25]
summary of original discussion with @daavoo:

Dependabot is enabled in both `py-template` and the project repos that use `py-template`. When you merge the PRs to update dependencies in the sub-projects, it ends up creating a merge conflict when the next `cruft` update PR is autogenerated. We want to keep dependabot enabled in both the template and sub-project repos (since each project will have its own dependencies that don't belong in the template), but should prefer using `cruft` to keep the template-related deps up to date.

---

Maybe we could add all dependencies that are set in the template to the ignore list in the generated repo's templated dependabot config. So shared dependencies would only be updated through the `iterative/py-template`'s dependabot config + cruft.

so `{{cookiecutter.project_name}}/.github/dependabot.yml` would need to contain `ignore` entries for everything listed in the template's `setup.cfg` (but this would not affect the py-template dependabot setup)

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

_Originally posted by @pmrowla in https://github.com/iterative/dvc-task/pull/30#discussion_r861461304_

**Comment by pmrowla** [comment]
My mistake, I didn't realize this had already been applied in the template. The problem was with the autogenerated cruft PR's failing in dvc-task due to conflicts.

**Comment by skshetry** [comment]
Thinking about this more, the upstream template generator should never make decisions for any dependencies update, we don't know whether something is compatible with those packages, and this updates all of the dependencies at once.

It should be left to the downstream packages themselves to deal with it. If you don't have the capacity, don't update test dependencies or set it to update monthly instead.
